### ISSUE TITLE
nmcli.device.wifi() Parse Failed

### ISSUE THREAD

**Issue by ryanteck** [ushiboy/nmcli#22]
Hi,

When running the ```nmcli.device.wifi()``` command I get the error Parse failed.

```Parse failed [        76:AC:B9:27:8A:44  Doge  Infra  10    270 Mbit/s  85      ▂▄▆█  WPA2     ]```

**Comment by ryanteck** [comment]
Figured out the cause, I'll however close the issue as it's actually working on the software I need it to.

nmcli on ubuntu reports back the BSSID as well where as on Debian it doesn't. So this issue affects Ubuntu and not Debian.

Output from ubuntu:
```*       76:AC:B9:27:8A:44  Doge  Infra  10    270 Mbit/s  89      ▂▄▆█  WPA2     
        74:AC:B9:27:8A:44  RTK   Infra  10    270 Mbit/s  89      ▂▄▆█  WPA2     
        8E:49:62:E1:0D:C5  --    Infra  10    65 Mbit/s   69      ▂▄▆_  WPA2     
        AE:AE:19:B1:55:56  --    Infra  10    65 Mbit/s   65      ▂▄▆_  WPA2 
```
Output from Debian:
```IN-USE  SSID  MODE   CHAN  RATE        SIGNAL  BARS  SECURITY 
        Doge  Infra  10    270 Mbit/s  65      ***   WPA2     
        --    Infra  10    65 Mbit/s   65      ***   WPA2     
        RTK   Infra  10    270 Mbit/s  62      ***   WPA2     
        --    Infra  10    65 Mbit/s   45      **    WPA2 
```

**Comment by ushiboy** [comment]
Thanks for the feedback.

I'll keep that in mind.
