### ISSUE TITLE
Seems to fail to parse wi-fi ssids with a space in the ssid.

### ISSUE THREAD

**Issue by ryanteck** [ushiboy/nmcli#24]
Hia,

I've found the library seems to fail parsing SSIDs when they have a space in the name. 

To replicate adding a space to an ssid seems to cause a parse error when running this code:

```
import nmcli
for network in nmcli.device.wifi():
    if(network.ssid != "--"):
        print(network.ssid)
```

I'll have a look at the regex if you'd like to figure out how to resolve it.

**Comment by ushiboy** [comment]
Thanks for the PR.
Version 0.4.1 has been released, try it out.

**Comment by ryanteck** [comment]
No problem, thanks for accepting it in.
