### ISSUE TITLE
Still get parse error on ssid with spaces

### ISSUE THREAD

**Issue by yakovyashfe** [ushiboy/nmcli#27]
File "/home/yacov/.local/lib/python3.8/site-packages/nmcli/data/device.py", line 74, in parse_include_bssid_line
    raise ValueError('Parse failed [%s]' % text)
ValueError: Parse failed [        40:B0:34:86:A1:F0  DIRECT-EF-HP OfficeJet Pro 6960   Infra  11    65 Mbit/s   49      **    WPA2      ]

**Comment by ushiboy** [comment]
Thanks for the feedback.
I'll check it.

**Comment by yakovyashfe** [comment]
forked and testing, I have an SSID with more than one space
'DIRECT-EF-HP OfficeJet Pro 6960'

**Comment by yakovyashfe** [comment]
ok, 
'^(\*|\s)\s* (\S*|\S+\s[\S]+|\S+\s[\S]+\s[\S]+) \s+(\S*)\s+(\d+)\s+(\d+)\sMbit/s\s+(\d+)\s+\S+\s+(.*)$'

this regex worked for me, still, it is not a good solution, since it doesn't check for more spaces in the name, so if the name is 
A A A A A A it will die.

**Comment by ushiboy** [comment]
I'm considering whether I can utilize the options of the nmcli command, as I feel the current way is limited.

**Comment by yakovyashfe** [comment]
Since this is my favorite nmcli package, after reviewing the rest I want to stick with it, I and my team are using it for a while and I would like to go on with it.
the main usage is to control wifi on an IoT device, therefore I need a combination of the ability to connect to wifi as well as starting hotspot for device config.
I would be happy to hear your input about changes that should be done.
I assume the best would be to start new issues, and others might come in.
I'm exploring the usage of D-BUS, also I think that since the output of nmcli device wifi list, as well as other output data, are all fixed-length fields it is unnecessary to use regex, it will be much easier to gust length split them.

**Comment by ushiboy** [comment]
Thanks for using it.
I've never used the hotspot feature before, so I don't have any ideas yet, but I'm interested.
I would like to prepare it as a separate issue for consideration.

**Comment by ushiboy** [comment]
Version 0.4.2 has been released, try it out.
