### ISSUE TITLE
Will you please help me?

### ISSUE THREAD

**Issue by xzj8b3** [ushiboy/nmcli#35]
I'm doing something wrong in Fedora 33 and can't set them correctly

nmcli con mod enp2s0 ipv4.ignore-auto-dns yes
nmcli con mod enp2s0 ipv4.dns "1.1.1.1, 1.0.0.1"
nmcli con mod enp2s0 ipv6.ignore-auto-dns yes
nmcli con mod enp2s0 ipv6.dns "2606:4700:4700::1111 ,2606:4700:4700::1001"

**Comment by ushiboy** [comment]
My environment is Raspberry PI OS, not Fedora, but the following sample code works correctly.

```python
import nmcli

try:
    nmcli.connection.modify('Conn1', {
        'ipv4.ignore-auto-dns': 'yes',
        'ipv4.dns': '8.8.8.8, 8.8.4.4',
        'ipv6.ignore-auto-dns': 'yes',
        'ipv6.dns': '2001:4860:4860::8888, 2001:4860:4860::8844'
        })
except Exception as e:
    print(e)
```

Please provide the error message, the version of Network Manager, and the version of the nmcli library.

**Comment by ushiboy** [comment]
Uh... Are you talking about the nmcli CLI, not the library?
If that is the case, the cause seems to be that you are specifying the interface name when you should be specifying the connection name.

**Comment by xzj8b3** [comment]
> Uh... Are you talking about the nmcli CLI, not the library?
> If that is the case, the cause seems to be that you are specifying the interface name when you should be specifying the connection name.

nmcli con mod Connessione via cavo1 ipv4.ignore-auto-dns yes

So how would it become that on cable I can not?

nmcli c modify 0c266bb6-94bd-4599-ab42-ee2564dec9b2 802-11-wireless.cloned-mac-address stable

I would like to apply the inpostings also on cable, but I keep getting the names wrong....ti bother to help please?

**Comment by ushiboy** [comment]
Maybe the connection name contains a white space? Why don't you try escaping it with a backslash? Like  `Connessione\ via\ cavo1`.

Anyway, this repository is for the PyPI module.
For more information on how to use CLI, see `man nmcli` or refer to the Network Manager repository.
