### ISSUE TITLE
I can not install nmcli

### ISSUE THREAD

**Issue by masakazu41525** [ushiboy/nmcli#36]
Please Excuse me.
I can't install this library
I installed this on ubuntu, but can't install and displayed error message

(venv) root@XXXX# pip install nmcli
Collecting nmcli
  Could not find a version that satisfies the requirement nmcli (from versions: )
No matching distribution found for nmcli
You are using pip version 9.0.1, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ushiboy** [comment]
From your error message, it looks like it is caused by an older version of pip.
Please run 'pip install --upgrade pip' to update your pip version and try the installation again.

**Comment by OrlandoArcapix** [comment]
This might also be due to your python version - nmcli needs python >= 3.7

**Comment by ushiboy** [comment]
OrlandoArcapix is right, the Python version may be a possible cause.
Please check the version of Python you are using.
