### ISSUE TITLE
Connection add not working

### ISSUE THREAD

**Issue by annadm99** [ushiboy/nmcli#58]
I just realized that connection add is not working properly. SSID is missing so it just throws an error. I solved the issue adding SSID parameter

**Comment by ushiboy** [comment]
@annadm99 
When using ssid, use the options argument.
The same applies when passing parameters such as passwords.

```python
nmcli.connection.add("wifi", {
    "ssid": "YourSSID",
}, ifname="wlan0")
```

Because `nmcli.connection.add` needs to support many different types of connections, it cannot be an interface that accepts Wifi-specific parameters.
