### ISSUE TITLE
UnicodeDecodeError on Raspberry

### ISSUE THREAD

**Issue by bernardolansing** [ushiboy/nmcli#63]
I was facing a string decoding error with this library when running it on a Raspberry. Its default encoding is not UTF-8, therefore some functions crashed with an unhandled exception. I have the code fixed here, how can I push it into the repository?

Edit: anyway it's a one-line fix, you can do it yourself. In file _system.py, `import locale` and in line 45, instead of `'utf-8'` put `locale.getpreferredencoding()`. That's all.

**Comment by bernardolansing** [comment]
It is ISO-8859-1.

**Comment by ushiboy** [comment]
PR: https://github.com/ushiboy/nmcli/pull/64

**Comment by ushiboy** [comment]
@bernardolansing 
I have released the fixes in version 1.2.0, so please try it out.
